apiVersion: apps/v1
kind: Deployment

metadata:
  name: devops-dashboard
  namespace: dev
  labels:
    app: devops-dashboard

spec:
  replicas: 2

  revisionHistoryLimit: 5   

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: devops-dashboard

  template:
    metadata:
      labels:
        app: devops-dashboard

    spec:
      terminationGracePeriodSeconds: 30

      imagePullSecrets:
        - name: dockerhub-secret

      containers:
        - name: devops-dashboard
          image: sejalkatre/devops-dashboard:main-7-a3a546a
          imagePullPolicy: Always
