apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: dev
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJzZWphbGthdHJlIiwicGFzc3dvcmQiOiJzZWphbGthdHJlIiwiZW1haWwiOiJzZWphbGthdHJlMDIxQGdtYWlsLmNvbSIsImF1dGgiOiJjMlZxWVd4cllYUnlaVHB6WldwaGJHdGhkSEpsIn19fQ==
